name: Test and Deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
      - name: setup postgresql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: tester1
          postgresql password: passw0rd!
      - name: install dependencies
        run: npm i
      - name: run tests
        run: PGDATABASE=test_db PGUSER=tester1 PGPASSWORD=passw0rd! npm t
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone and checkout repo
        uses: actions/checkout@v3
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@3.12.12
        with: 
          heroku_api_key: $${{secrets.HEROKU_API_KEY}}
          heroku_app_name: $${{secrets.HEROKU_APP_NAME}}
          heroku_email: $${{secrets.HEROKU_EMAIL}}
          